/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#7bd0ff",
        "on-primary-fixed-variant": "#004c69",
        "on-secondary": "#003825",
        "tertiary-fixed-dim": "#ffb783",
        "on-background": "#e3e2e6",
        "on-secondary-fixed-variant": "#005137",
        "on-secondary-fixed": "#002114",
        "on-secondary-container": "#00452e",
        primary: "#8ed5ff",
        "surface-container": "#1f1f23",
        "on-surface-variant": "#bdc8d1",
        "on-primary": "#00354a",
        "on-primary-container": "#004965",
        "error-container": "#93000a",
        "surface-container-low": "#1b1b1f",
        "surface-variant": "#343538",
        "secondary-fixed": "#68fcbf",
        "surface-container-lowest": "#0d0e11",
        "on-primary-fixed": "#001e2c",
        "tertiary-container": "#ff9846",
        "primary-container": "#38bdf8",
        "primary-fixed-dim": "#7bd0ff",
        surface: "#121316",
        error: "#ffb4ab",
        "on-surface": "#e3e2e6",
        "secondary-fixed-dim": "#45dfa4",
        "inverse-primary": "#00668a",
        background: "#121316",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#6d3500",
        "inverse-surface": "#e3e2e6",
        "secondary-container": "#00bd85",
        outline: "#87929a",
        "outline-variant": "#3e484f",
        tertiary: "#ffc094",
        "surface-bright": "#38393c",
        "surface-container-high": "#292a2d",
        "tertiary-fixed": "#ffdcc5",
        secondary: "#45dfa4",
        "on-tertiary-fixed-variant": "#713700",
        "on-tertiary-fixed": "#301400",
        "surface-container-highest": "#343538",
        "inverse-on-surface": "#303034",
        "on-tertiary": "#4f2500",
        "primary-fixed": "#c4e7ff",
        "on-error": "#690005",
        "surface-dim": "#121316",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "sidebar-width": "16rem",
        "rail-width": "4.5rem",
        "inspector-width": "20rem",
        "gutter-desktop": "1rem",
        "gutter-mobile": "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["JetBrains Mono", "SF Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-code-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Inter", "sans-serif"],
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "badge-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
      },
      fontSize: {
        "badge-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-code-sm": ["11px", { lineHeight: "14px", letterSpacing: "0", fontWeight: "400" }],
        "label-code-md": ["12px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
      },
      boxShadow: {
        "hud-capsule": "0 12px 32px -4px rgba(0, 0, 0, 0.75), 0 0 0 1px #333842",
        "modal-dialog": "0 24px 64px -8px rgba(0, 0, 0, 0.9), 0 0 0 1px #2B303B",
      },
    },
  },
  plugins: [],
};
